app:
  build: .
  links:
    - rabbitmq
    - wildfly
  environment:
    ALLOWED_ORIGINS: '[".*"]'

user-works:
  build: ../user-works
  links:
    - rabbitmq
    - wildfly
  environment:
    USER_WORKS_DATOMIC_URI: datomic:dev://datomic:4334/user-works
    INITIALIZE_DATOMIC: "true"

wildfly:
  image: quay.io/democracyworks/wildfly:8.2.0.Final
  links:
    - rabbitmq
    - datomic
  ports:
    - "59990:9990"
    - "58080:8080"
    - "1527:1527"
  environment:
    ADMIN_USERNAME: admin
    ADMIN_PASSWORD: admin

rabbitmq:
  image: rabbitmq:3.5.3-management
  ports:
    - "45672:5672"
    - "55672:15672"
  hostname: rabbitmq

datomic:
  image: quay.io/democracyworks/datomic-tx:0.9.5327
  ports:
    - "4334:4334"
    - "4335:4335"
    - "4336:4336"
  environment:
    ALT_HOST: localhost
  hostname: datomic
